// Auto-generated by build.py - do not edit manually
// Run `python3 build.py` to regenerate

var PORTFOLIO_AUTO_DATA = {
  translations: {
    zh: {
      "auto-wr-01-cold-start-paradox-tag": `产品分析`,
      "auto-wr-01-cold-start-paradox-title": `C端AI产品的冷启动悖论`,
      "auto-wr-02-companionship-wall-tag": `产品分析`,
      "auto-wr-02-companionship-wall-title": `陪伴之墙：AI 时代的孤独与情感机制演进`,
      "auto-wr-Songkran_Final_2026-tag": `文化观察`,
      "auto-wr-Songkran_Final_2026-title": `SONGKRAN: Field Notes on Legitimacy, Joy, and Who Gets to Take Up Space`,
      "auto-wr-decluttering_retention_conversion-tag": `产品分析`,
      "auto-wr-decluttering_retention_conversion-title": `少即是多：C端界面降噪如何撬动用户停留与转化`,
      "auto-wr-parasocial_analysis-tag": `产品分析`,
      "auto-wr-parasocial_analysis-title": `直播间的社交引擎：Parasocial Relationship 如何驱动互动与营收`,
      "auto-sw-philforum-desc": `沉浸式思想圆桌应用。把真实问题交给历史上的哲学家，看他们如何回应、辩论、碰撞。`,
      "auto-sw-philforum-name": `The Philosopher's Forum`,
      "auto-sw-travelmap-desc": `一个帮你找到最佳旅行时机的交互工具。结合气候数据与个人偏好，可视化呈现全球目的地的适宜出行窗口。`,
      "auto-sw-travelmap-name": `Levi's Travel Map`,
    },
    en: {
      "auto-wr-01-cold-start-paradox-tag": `Product Analysis`,
      "auto-wr-01-cold-start-paradox-title": `The Cold Start Paradox of Consumer AI Products`,
      "auto-wr-02-companionship-wall-tag": `Product Analysis`,
      "auto-wr-02-companionship-wall-title": `The Companionship Wall`,
      "auto-wr-Songkran_Final_2026-tag": `Cultural Observation`,
      "auto-wr-Songkran_Final_2026-title": `SONGKRAN: Field Notes on Legitimacy, Joy, and Who Gets to Take Up Space`,
      "auto-wr-decluttering_retention_conversion-tag": `Product Analysis`,
      "auto-wr-decluttering_retention_conversion-title": `The Leverage of Less: How UI Decluttering Drives Retention & Conversion`,
      "auto-wr-parasocial_analysis-tag": `Product Analysis`,
      "auto-wr-parasocial_analysis-title": `The Social Engine of Live Streaming: How Parasocial Relationships Drive Engagement & Revenue`,
      "auto-sw-philforum-desc": `An immersive roundtable experience. Bring your questions to history's greatest thinkers and watch them respond, debate, and collide.`,
      "auto-sw-philforum-name": `The Philosopher's Forum`,
      "auto-sw-travelmap-desc": `An interactive tool to find your ideal travel timing. Combines climate data with personal preferences to visualize the best windows for destinations worldwide.`,
      "auto-sw-travelmap-name": `Levi's Travel Map`,
    },
  },
  writings: [
    {
      id: "01-cold-start-paradox",
      titleKey: "auto-wr-01-cold-start-paradox-title",
      tagKey: "auto-wr-01-cold-start-paradox-tag",
      langs: {"zh": {"file": "source/文章/01-cold-start-paradox_zh.html"}, "en": {"file": "source/文章/01-cold-start-paradox_en.html"}},
    },
    {
      id: "02-companionship-wall",
      titleKey: "auto-wr-02-companionship-wall-title",
      tagKey: "auto-wr-02-companionship-wall-tag",
      langs: {"zh": {"file": "source/文章/02-companionship-wall_zh.html"}, "en": {"file": "source/文章/02-companionship-wall_en.html"}},
    },
    {
      id: "Songkran_Final_2026",
      titleKey: "auto-wr-Songkran_Final_2026-title",
      tagKey: "auto-wr-Songkran_Final_2026-tag",
      langs: {"zh": null, "en": {"file": "source/文章/Songkran_Final_2026.html"}},
    },
    {
      id: "decluttering_retention_conversion",
      titleKey: "auto-wr-decluttering_retention_conversion-title",
      tagKey: "auto-wr-decluttering_retention_conversion-tag",
      langs: {"zh": {"file": "source/文章/decluttering_retention_conversion_zh.html"}, "en": {"file": "source/文章/decluttering_retention_conversion_en.html"}},
    },
    {
      id: "parasocial_analysis",
      titleKey: "auto-wr-parasocial_analysis-title",
      tagKey: "auto-wr-parasocial_analysis-tag",
      langs: {"zh": {"file": "source/文章/parasocial_analysis.html"}, "en": {"file": "source/文章/parasocial_analysis_en.html"}},
    },
  ],
  smallWorks: [
    {
      id: "travelmap",
      nameKey: "auto-sw-travelmap-name",
      descKey: "auto-sw-travelmap-desc",
      file: "travel-map/",
      productDesc: "source/\u5c0f\u4f5c\u54c1/levi's travel map/product-description.md",
      productDescInline: {"zh": "Levi's Travel Map 是一款旅行时机决策工具，帮助用户根据气候偏好和个人约束条件，找到全球目的地的最佳出行窗口。用户选择目的地后，工具会整合历史气候数据（温度、降水、日照），结合用户对拥挤度、预算和假期的偏好，可视化呈现每月的综合适宜度评分。界面采用沉浸式全屏欢迎页 + 横向滚动时间线 + 动态评分卡片，让抽象的\"什么时候去最好\"变成可交互、可比较的直观体验。它适合旅行规划、灵感探索和行程决策。", "en": "Levi's Travel Map is a travel timing decision tool that helps users find the best window to visit destinations worldwide based on climate preferences and personal constraints. After selecting a destination, the tool integrates historical climate data (temperature, precipitation, sunshine) with user preferences on crowding, budget, and vacation availability to visualize a monthly composite suitability score. The interface features an immersive full-screen welcome, horizontal-scrolling timeline, and dynamic scoring cards — turning the abstract question of \"when should I go\" into an interactive, comparable, and intuitive experience. Ideal for trip planning, travel inspiration, and itinerary decisions."},
    },
    {
      id: "philforum",
      nameKey: "auto-sw-philforum-name",
      descKey: "auto-sw-philforum-desc",
      file: "source/\u5c0f\u4f5c\u54c1/the philosopher's forum/the philosopher's forum.html",
      productDesc: "source/\u5c0f\u4f5c\u54c1/the philosopher's forum/product-description.md",
      productDescInline: {"zh": "The Philosopher's Forum 是一款沉浸式思想圆桌应用，让用户把真实问题交给历史上的哲学家共同回应。用户输入一个关于人生、知识、道德、自我或信仰的问题后，系统会匹配相关哲学家，以对话形式呈现他们的立场、语气和代表性观点。界面采用克制的编辑式设计，结合人物席位、讨论流、引用回复和哲学家档案，让抽象思想变得可比较、可追问、可继续讨论。它适合灵感探索、哲学入门、写作启发和深度思考练习。", "en": "The Philosopher's Forum is an immersive roundtable experience where users bring living questions to history's greatest thinkers. Enter a question about meaning, knowledge, morality, identity, or faith, and the app gathers relevant philosophers into a conversational debate. Each response reflects a distinct school of thought, voice, and intellectual stance, while profile dossiers offer quick context on each thinker's era, work, and worldview. With focused chat, reply, quote, and comparison flows, the product turns abstract philosophy into an approachable, interactive space for reflection, learning, writing inspiration, and deeper inquiry."},
    },
  ],
};